[package]
name = "algorithmic"
version = "0.1.1"
entrypoint = "algorithmic.typ"
authors = ["Jade Lovelace"]
license = "MIT"
repository = "https://github.com/lf-/typst-algorithmic"
exclude = ["docs/assets/*", "*.pdf"]
description = "Algorithm pseudocode typesetting for Typst, inspired by algorithmicx in LaTeX"
